apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cekit-builder
  labels:
    {{- include "cekit-builder.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  source:
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.ref }}
      contextDir: {{ .Values.git.contextDir }}
  strategy:
    dockerStrategy:
      dockerfilePath: "./Containerfile"
  output:
    to:
      kind: DockerImage
      name: {{ .Values.registry.hostname }}/{{ .Values.registry.namespace }}/{{ .Values.registry.builderImage }}:{{ .Values.registry.builderTag }}