apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: postgresql-15-c9s
  namespace: imported-images
  labels:
    {{- include "cekit-builder.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.io/sclorg/postgresql-15-c9s:c9s
    generation: 1
    importPolicy:
      importMode: Legacy
    name: c9s
    referencePolicy:
      type: Source