apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: imported-images-image-puller
  namespace: imported-images
  labels:
    {{- include "cekit-builder.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "12"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts