apiVersion: v1
kind: ServiceAccount
metadata:
  name: cekit-builder
  namespace: cekit-images
  labels:
    {{- include "cekit-builder.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"